Repository Datadvisor/api, pull requests merged in 2022-12, with the labels that each got.

#52 refactor: Adding email confirmation enhancements
  prisma/migrations/20221201194815_userverified/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.spec.ts
  src/auth/auth.service.spec.ts
  src/auth/decorators/auth-verified-user.decorator.ts
  src/auth/guards/auth-verified-user.guard.ts
  src/email-confirmation/email-confirmation.controller.spec.ts
  src/email-confirmation/email-confirmation.service.spec.ts
  src/email-confirmation/email-confirmation.service.ts
  src/reset-password/reset-password.controller.spec.ts
  src/reset-password/reset-password.service.spec.ts
  src/seeder/seeder.service.ts
  src/users/ro/user.ro.ts
  src/users/user.controller.spec.ts
  src/users/users.controller.spec.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/auth/auth.e2e-spec.ts
  test/email-confirmation/email-confirmation.e2e-spec.ts
Labels: enhancement

#53 fix: bad default value for cors origins and cors headers
  src/config/api.config.ts
Labels: bug

#54 fix: remove cors headers
  src/config/api.config.ts
  src/main.ts
Labels: bug

#57 feat: added worker module
  .env.example
  package.json
  src/app.module.ts
  src/config/api.config.ts
  src/email/dto/send-email.dto.ts
  src/main.ts
  src/scrapper/scrapper.module.ts
  src/worker/views/worker-activities-report-email.view.ejs
  src/worker/worker.module.ts
  src/worker/worker.service.ts
  tsconfig.build.json
  yarn.lock
Labels: enhancement

#58 refactor: rewrite some module codes
  src/auth/decorators/auth-owner.decorator.ts
  src/auth/decorators/auth-user.decorator.ts
  src/auth/decorators/auth-verified-user.decorator.ts
  src/auth/guards/auth-user.guard.ts
  src/auth/guards/auth-verified-user.guard.ts
  src/contact/contact.service.ts
  src/email-confirmation/email-confirmation.service.spec.ts
  src/email-confirmation/email-confirmation.service.ts
  src/reset-password/reset-password.service.ts
  src/scrapper/scrapper.module.ts
  src/users/user.controller.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/utils/utils.ts
  src/worker/worker.service.ts
Labels: enhancement

#59 docs: updated swagger documentation to display enum values in users module
  src/users/ro/user-activities-report-preferences.ro.ts
  src/users/ro/user-preferences.ro.ts
Labels: documentation

#60 feat: added payment module with subscription routes
  .env.example
  .github/workflows/typescript-test.yml
  package.json
  prisma/migrations/20221228062344_premium_user_system/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/config/api.config.ts
  src/doc/doc.ts
  src/payment/dto/post-payment-details.dto.ts
  src/payment/payment.controller.ts
  src/payment/payment.module.ts
  src/payment/payment.service.ts
  src/users/dto/subscribe.dto.ts
  src/users/user.controller.ts
  src/users/users.module.ts
  yarn.lock
Labels: enhancement

#61 fix: file validator size and accepted file type
  src/scrapper/scrapper.controller.ts
Labels: bug
